"""Local occupational vocabulary; matches must occur in saved job-side text."""
# Canonical tool -> multilingual aliases. Avoid ambiguous standalone abbreviations.
PROFESSIONAL_TOOLS = {
 'SolidWorks':['solidworks'], 'AutoCAD':['autocad'], 'Siemens NX':['siemens nx'],
 'Creo':['ptc creo','creo'], 'MATLAB':['matlab'], 'Simulink':['simulink'],
 'COMSOL':['comsol'], 'Revit':['revit'], 'ArchiCAD':['archicad'],
 'Civil 3D':['civil 3d'], 'Navisworks':['navisworks'], 'QGIS':['qgis'], 'ArcGIS':['arcgis'],
 'EPLAN':['eplan'], 'Altium Designer':['altium designer'], 'KiCad':['kicad'],
 'LTspice':['ltspice'], 'TIA Portal':['tia portal'], 'SIMATIC':['simatic'],
 'CODESYS':['codesys'], 'TwinCAT':['twincat'], 'LabVIEW':['labview'],
 'CANoe':['canoe'], 'CANalyzer':['canalyzer'], 'OPC UA':['opc ua','opc-ua'],
 'Modbus':['modbus'], 'PROFINET':['profinet'], 'Verilog':['verilog'], 'VHDL':['vhdl'],
 'SAP S/4HANA':['sap s/4hana','sap s/4 hana'], 'SAP FI':['sap fi'], 'SAP CO':['sap co'],
 'SAP MM':['sap mm'], 'SAP SD':['sap sd'], 'DATEV':['datev'],
 'QuickBooks':['quickbooks'], 'Excel':['excel','microsoft excel'],
 'Power BI':['power bi','powerbi'], 'Tableau':['tableau'], 'SPSS':['spss'],
 'Salesforce':['salesforce'], 'HubSpot':['hubspot'], 'Google Analytics':['google analytics','ga4'],
 'Google Ads':['google ads'], 'Meta Ads':['meta ads'], 'SEMrush':['semrush'],
 'Adobe Photoshop':['photoshop'], 'Adobe Illustrator':['adobe illustrator'],
 'InDesign':['indesign'], 'Figma':['figma'], 'Premiere Pro':['premiere pro'],
 'After Effects':['after effects'], 'Blender':['blender'],
 'Workday':['workday'], 'Personio':['personio'], 'SAP SuccessFactors':['successfactors'],
 'Jira':['jira'], 'Confluence':['confluence'], 'MS Project':['ms project','microsoft project'],
 'Primavera P6':['primavera p6'], 'Minitab':['minitab'],
 'HPLC':['hplc','高效液相色谱'], 'GC-MS':['gc-ms','气相色谱质谱'],
 'PCR':['pcr','聚合酶链式反应'], 'ELISA':['elisa'], 'LIMS':['lims'],
 'HL7':['hl7'], 'FHIR':['fhir'], 'DICOM':['dicom'],
 'Selenium':['selenium'], 'Cypress':['cypress'], 'Playwright':['playwright'],
 'Postman':['postman'], 'JMeter':['jmeter'], 'Wireshark':['wireshark'],
 'Splunk':['splunk'], 'Burp Suite':['burp suite'], 'Nessus':['nessus'],
}
PROFESSIONAL_METHODS = {
 'Finite Element Analysis':['finite element analysis','finite-element analysis','有限元分析'],
 'Computational Fluid Dynamics':['computational fluid dynamics','计算流体力学'],
 'CNC Machining':['cnc machining','cnc-programmierung','数控加工'],
 'PLC':['sps-programmierung','可编程逻辑控制器','plc programming'],
 'Lean Manufacturing':['lean manufacturing','精益生产'],
 'Six Sigma':['six sigma','六西格玛'], 'FMEA':['fmea','失效模式与影响分析'],
 'APQP':['apqp'], 'PPAP':['ppap'], 'GD&T':['gd&t','geometric dimensioning and tolerancing'],
 'ISO 9001':['iso 9001'], 'ISO 13485':['iso 13485'], 'IATF 16949':['iatf 16949'],
 'GMP':['gmp','good manufacturing practice','良好生产规范'],
 'GCP (Clinical Practice)':['good clinical practice','临床试验质量管理规范'],
 'IFRS':['ifrs','国际财务报告准则'], 'German GAAP (HGB)':['hgb','handelsgesetzbuch'],
 'Financial Reporting':['financial reporting','财务报告','finanzberichterstattung'],
 'Payroll':['payroll','薪酬核算','lohnabrechnung'],
 'SEO':['seo','search engine optimization','搜索引擎优化','suchmaschinenoptimierung'],
 'Supply Chain Management':['supply chain management','供应链管理'],
 'Inventory Management':['inventory management','库存管理','bestandsmanagement'],
 'Clinical Trials':['clinical trials','klinische studien','临床试验'],
 'Patient Care':['patient care','患者护理','patientenversorgung'],
 'Instructional Design':['instructional design','教学设计'],
 'User Research':['user research','用户研究','nutzerforschung'],
 'Scrum':['scrum'], 'Kanban':['kanban'], 'ITIL':['itil'],
}
# Occupational title, detailed role, primary track. Specific roles precede broad IT rules.
OCCUPATION_ROLES = [
 (r'mechanical.engineer|maschinenbauingenieur|konstruktionsingenieur|机械工程|机械设计','Mechanical Engineering','Mechanical & Manufacturing'),
 (r'manufacturing.engineer|production.engineer|fertigungsingenieur|produktionsingenieur|制造工程|生产工程','Manufacturing Engineering','Mechanical & Manufacturing'),
 (r'electrical.engineer|electronics.engineer|elektroingenieur|elektrotechnik|电气工程|电子工程','Electrical Engineering','Electrical & Automation'),
 (r'automation.engineer|automatisierungsingenieur|sps.programmierer|自动化工程','Automation Engineering','Electrical & Automation'),
 (r'civil.engineer|structural.engineer|bauingenieur|土木工程|结构工程','Civil Engineering','Construction & Architecture'),
 (r'architectural.designer|bauarchitekt|建筑师|建筑设计','Architecture','Construction & Architecture'),
 (r'quality.engineer|quality.manager|qualitätsingenieur|qualitätsmanager|质量工程|质量管理','Quality Engineering','Validation & QA'),
 (r'accountant|buchhalter|bilanzbuchhalter|会计|审计师|auditor','Accounting / Audit','Finance & Accounting'),
 (r'financial.analyst|finance.manager|financial.controller|business.controller|^(?:senior |junior )?controller\b|财务分析|财务经理','Finance / Controlling','Finance & Accounting'),
 (r'marketing|市场营销|市场推广|seo.specialist','Marketing','Marketing & Communications'),
 (r'sales.manager|sales.engineer|account.executive|vertriebs|销售|business.development','Sales / Business Development','Sales & Customer Success'),
 (r'customer.success|customer.support|kundenservice|客户成功|客户支持','Customer Success / Support','Sales & Customer Success'),
 (r'recruiter|recruiting|personalreferent|human.resources|\bhr.manager|招聘|人力资源','Human Resources','People & HR'),
 (r'supply.chain|logistics|logistik|procurement|einkäufer|供应链|物流|采购','Supply Chain / Logistics','Supply Chain & Operations'),
 (r'operations.manager|betriebsleiter|运营经理','Operations','Supply Chain & Operations'),
 (r'clinical.research|clinical.trial|klinische.forschung|临床研究','Clinical Research','Healthcare & Life Sciences'),
 (r'\bnurse\b|pflegefach|krankenpfleger|护士|护理师','Nursing','Healthcare & Life Sciences'),
 (r'physician|\barzt\b|ärztin|医生|pharmacist|apotheker|药剂师','Clinical Practice','Healthcare & Life Sciences'),
 (r'laboratory.technician|lab.technician|laborant|实验员|实验室技术','Laboratory Science','Healthcare & Life Sciences'),
 (r'graphic.designer|ux.designer|ui.designer|product.designer|grafikdesigner|平面设计|交互设计|用户体验设计','Design / UX','Design & Creative'),
 (r'teacher|educator|lehrer|lehrerin|教师|教学设计','Education / Training','Education & Training'),
 (r'lawyer|legal.counsel|rechtsanwalt|jurist|律师|法务','Legal','Legal & Compliance'),
 (r'compliance.officer|compliance.manager|合规专员|合规经理','Compliance','Legal & Compliance'),
 (r'cyber.security|cybersecurity|security.analyst|it.security|网络安全|信息安全','Cybersecurity','IT Security & Infrastructure'),
 (r'system.administrator|systemadministrator|network.engineer|网络工程|系统管理员','IT Infrastructure','IT Security & Infrastructure'),
]
